# Generated by Django 5.0.4 on 2024-08-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_order_desc_orderupdate_update_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
